### ISSUE TITLE
Change BFT to BetterFletchingTable in the filenames

### ISSUE THREAD

**Issue by allanonmage** [EclipseStudiosMC/better_fletching_table#2]
I am modifying the datapack and resourcepack filenames so that when I'm looking through datapacks and mods at a later date, I won't be like "What in the world is a BFT?!?!", and figured I'd give you my 2 cents that it might be a good idea moving forward.

**Comment by ElGeroIngles** [comment]
You can change the names of both the datapack and resourcepack to whatever you want, it doesn't matter. Also, it would be cool to maintain this issues report page to only issues reports, I don't want to sound toxic or anything, I just want to maintain these things content to what they are supoused to.

**Comment by allanonmage** [comment]
Sometimes in Github the author/project manager sets up multiple different things under issues like "Feature Requests" or "Suggestions", which amount to some custom tags for filtering things.  I didn't see that option, so I made it apparent that this was a suggestion, not a bug report.
