### ISSUE TITLE
Two textures break mipmapping

### ISSUE THREAD

**Issue by BobzBlue** [EclipseStudiosMC/better_fletching_table#3]
[16:51:52] [Worker-ResourceReload-10/WARN]:
 Texture minecraft:custom/ui/gui with size 700x292 limits mip level from 4 to 2
[16:51:52] [Worker-ResourceReload-10/WARN]:
 Texture minecraft:custom/ui/menu with size 175x73 limits mip level from 2 to 0
[16:51:52] [Worker-ResourceReload-10/WARN]:
 minecraft:textures/atlas/blocks.png: dropping miplevel from 4 to 0, because of minimum power of two: 1

ui/gui and ui/menu cause mipmapping to break. There is a mod that universally fixes this sort of issue, but that mod is not up to date. Mipmapping is a form of anti-aliasing, Minecraft benefits from this visually.

**Comment by ElGeroIngles** [comment]
Please, as stayed in the description, report all issues in the [discord server](https://discord.gg/4pYjW9btNc) please, I won't fix any issues reported in GitHub, sorry.
